<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.195" timestamp="2023-01-07T09:21:09.391256" hostname="DESKTOP-OU09NQ4"><testcase classname="test_mark_custom" name="test_verify_001" time="0.003"><failure message="assert 10 == 20">@pytest.mark.smoke
    def test_verify_001():
        x = 10
        y = 20
&gt;       assert x == y
E       assert 10 == 20

test_mark_custom.py:8: AssertionError</failure></testcase><testcase classname="test_mark_custom" name="test_verify_002" time="0.001" /><testcase classname="test_mark_custom" name="test_verify_003" time="0.002" /></testsuite></testsuites>